1. Importar librerías

In [78]:
import pandas as pd         # Manipulación y análisis de datos para el CVS
import numpy as np          # Operaciones numéricas y manejo de valores nulos
import plotly.express as px # Gráficos interactivos y visualizaciones dinámicas
import seaborn as sns       # Gráficos estadísticos
import matplotlib.pyplot as plt # Gráficos básicos

2. Cargar archivo para visualización de los datos

In [79]:
df = pd.read_csv("Violencia_Intrafamiliar_Policía_Nacional1.csv")
df.head()

,DEPARTAMENTO,MUNICIPIO,CODIGO DANE,ARMAS MEDIOS,FECHA HECHO,GENERO,GRUPO ETARIO,CANTIDAD
0,CALDAS,Manizales (CT),17001000,SIN EMPLEO DE ARMAS,10/03/2026,FEMENINO,ADULTOS,2
1,ATLÁNTICO,Malambo,8433000,SIN EMPLEO DE ARMAS,15/03/2026,FEMENINO,ADULTOS,1
2,ATLÁNTICO,Luruaco,8421000,SIN EMPLEO DE ARMAS,09/03/2026,FEMENINO,ADULTOS,1
3,HUILA,Pitalito,41551000,SIN EMPLEO DE ARMAS,14/03/2026,FEMENINO,ADULTOS,1
4,CUNDINAMARCA,Anapoima,25035000,SIN EMPLEO DE ARMAS,28/01/2026,FEMENINO,ADULTOS,1

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682558 entries, 0 to 682557
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   DEPARTAMENTO  682558 non-null  object
 1   MUNICIPIO     682554 non-null  object
 2   CODIGO DANE   682558 non-null  int64
 3   ARMAS MEDIOS  682558 non-null  object
 4   FECHA HECHO   682558 non-null  object
 5   GENERO        679671 non-null  object
 6   GRUPO ETARIO  681416 non-null  object
 7   CANTIDAD      682558 non-null  int64
dtypes: int64(2), object(6)
memory usage: 41.7+ MB

In [81]:
data = df.drop(columns=['CODIGO DANE'])

In [82]:
data["FECHA HECHO"] = pd.to_datetime(data["FECHA HECHO"], format="%d/%m/%Y")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682558 entries, 0 to 682557
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   DEPARTAMENTO  682558 non-null  object
 1   MUNICIPIO     682554 non-null  object
 2   ARMAS MEDIOS  682558 non-null  object
 3   FECHA HECHO   682558 non-null  datetime64[ns]
 4   GENERO        679671 non-null  object
 5   GRUPO ETARIO  681416 non-null  object
 6   CANTIDAD      682558 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 36.5+ MB

In [83]:
data.head()

,DEPARTAMENTO,MUNICIPIO,ARMAS MEDIOS,FECHA HECHO,GENERO,GRUPO ETARIO,CANTIDAD
0,CALDAS,Manizales (CT),SIN EMPLEO DE ARMAS,2026-03-10,FEMENINO,ADULTOS,2
1,ATLÁNTICO,Malambo,SIN EMPLEO DE ARMAS,2026-03-15,FEMENINO,ADULTOS,1
2,ATLÁNTICO,Luruaco,SIN EMPLEO DE ARMAS,2026-03-09,FEMENINO,ADULTOS,1
3,HUILA,Pitalito,SIN EMPLEO DE ARMAS,2026-03-14,FEMENINO,ADULTOS,1
4,CUNDINAMARCA,Anapoima,SIN EMPLEO DE ARMAS,2026-01-28,FEMENINO,ADULTOS,1

In [84]:
print(data['ARMAS MEDIOS'].describe())
print(data['GENERO'].describe())
print(data['GRUPO ETARIO'].describe())

count           682558
unique               9
top       CONTUNDENTES
freq            301376
Name: ARMAS MEDIOS, dtype: object
count       679671
unique           3
top       FEMENINO
freq        509255
Name: GENERO, dtype: object
count      681416
unique          3
top       ADULTOS
freq       624263
Name: GRUPO ETARIO, dtype: object

In [85]:
print(data["ARMAS MEDIOS"].unique())
print(data["GENERO"].unique())
print(data["GRUPO ETARIO"].unique())

['SIN EMPLEO DE ARMAS' 'NO REPORTADO' 'PUNZANTES' 'CONTUNDENTES'
 'CORTANTES' 'CORTOPUNZANTES' 'ESCOPOLAMINA' 'ARMA BLANCA / CORTOPUNZANTE'
 'ARMA DE FUEGO']
['FEMENINO' 'MASCULINO' nan 'NO REPORTA']
['ADULTOS' 'MENORES' nan 'ADOLESCENTES']